const fs=require('fs'),path=require('path');const puppeteer=require('D:/Work/Codex/Hackathon Projects/LumaLoad/node_modules/puppeteer');const dir=__dirname,sleep=ms=>new Promise(r=>setTimeout(r,ms));const timeline=JSON.parse(fs.readFileSync(path.join(dir,'timeline.json'),'utf8'));
async function click(p,text){await p.waitForFunction(t=>[...document.querySelectorAll('button,[role="button"],a,div')].some(x=>x.offsetParent!==null&&x.innerText?.includes(t)),{timeout:45000},text);for(const b of await p.$$('button,[role="button"],a,div'))if(await b.evaluate((x,t)=>x.offsetParent!==null&&x.innerText?.includes(t),text)){await b.evaluate(x=>x.scrollIntoView({block:'center',behavior:'smooth'}));await sleep(350);await b.click();return;}throw Error(text)}
(async()=>{const b=await puppeteer.launch({headless:true});const p=await b.newPage();await p.setViewport({width:1920,height:1080});p.on('pageerror',e=>console.log('PAGE ERROR',e.message));await p.goto('https://web-eight-phi-69.vercel.app',{waitUntil:'networkidle2',timeout:60000});await p.waitForFunction(()=>document.body.innerText.includes('PostgreSQL'),{timeout:60000});const cdp=await p.createCDPSession();let cur=null,n=0;cdp.on('Page.screencastFrame',async e=>{if(cur){const f=path.join(cur.folder,`${String(n++).padStart(6,'0')}.jpg`);fs.writeFileSync(f,Buffer.from(e.data,'base64'));cur.frames.push({file:f,t:(Date.now()-cur.start)/1000})}await cdp.send('Page.screencastFrameAck',{sessionId:e.sessionId})});await cdp.send('Page.startScreencast',{format:'jpeg',quality:88,everyNthFrame:1});
async function scene(id,work){const s=timeline.find(x=>x.id===id),folder=path.join(dir,'capture',id);fs.mkdirSync(folder,{recursive:true});cur={folder,frames:[],start:Date.now()};await p.screenshot({path:path.join(folder,'initial.jpg')});cur.frames.push({file:path.join(folder,'initial.jpg'),t:0});await work();const elapsed=(Date.now()-cur.start)/1000;if(elapsed>s.sceneDuration)throw Error(id+' exceeded');await sleep((s.sceneDuration-elapsed)*1000);fs.writeFileSync(path.join(folder,'manifest.json'),JSON.stringify({duration:s.sceneDuration,frames:cur.frames}));cur=null;console.log('Recorded',id)}
await scene('02-intake',async()=>{await click(p,'Seed 4 Tamil Nadu Preset Jobs');await sleep(18000)});
await scene('03-advice',async()=>{await sleep(12000)});
await scene('04-approval',async()=>{await sleep(12000)});
await scene('05-repair',async()=>{await sleep(12000)});
await cdp.send('Page.stopScreencast');await b.close()})();
